### ISSUE TITLE
bot binds to empty channel

### ISSUE THREAD

**Issue by L0615T1C5-216AC-9437** [Corrupted-Inc/corrupted-mainframe#9]
if a bot is told to !play in a channel it doesnt have access to, it will bind to said channel then state `Error
You must be in the voice channel to use this command!` on any subsequent query until it is told to !stop on said restricted channel

**Comment by TheCorruptedKing** [comment]
Me when SSLEngine bad
![unknown (2)](https://user-images.githubusercontent.com/66529179/129307116-166338bb-3e32-4ac5-a2a8-cf6788381fac.png)

**Comment by blahblahbloopster** [comment]
A channel where the bot doesn't have permission to join or the user?

**Comment by TheCorruptedKing** [comment]
A temporary fix was pushed, the bot now says which channel it is binded to. Will be worked on later so it doesn't happen again.

**Comment by TheCorruptedKing** [comment]
Closed due to bug fixes.
